### ISSUE TITLE
Add error checking for duplicate files names for input files

### ISSUE THREAD

**Issue by apetkau** [apetkau/core-phylogenomics#12]
Add error checking for duplicate files names for input files.  In particular, make sure the situation of running the pipeline with a reference and fastq file with duplicate names causes an error before the pipeline runs.  That is if the pipeline is run with:

`snp_phylogenomics_control --mode mapping --input-dir input/ --reference reference.fasta --output out`

where the following files are within **input/**:
```
sample1.fastq
sample2.fastq
reference.fastq
```

(so **reference.fasta** and **reference.fastq** are the same name) then make sure that an error is printed before the pipeline runs.

**Comment by csieffert** [comment]
This error checking has been implemented as a submodule in the CopyInputFastq.pm file.  Will call die and print an error message to the screen when duplicate file names are encountered.
