### ISSUE TITLE
Remove --contig-dir option

### ISSUE THREAD

**Issue by apetkau** [apetkau/core-phylogenomics#18]
Remove the --contig-dir option and associated documentation, for example at https://github.com/apetkau/core-phylogenomics/blob/master/scripts/snp_phylogenomics_control.pl#L654.  This did never work quite right so should be removed so no user attempts to use this mode.

**Comment by csieffert** [comment]
Removed --contig-dir option in commit 6e81f31f1794870c81751253189853fcb78aad1d.  Pull request sent to original branch.
