### ISSUE TITLE
vcf2core stage causes delays when generating core genome images

### ISSUE THREAD

**Issue by apetkau** [apetkau/core-phylogenomics#5]
vcf2core stage causes delays when generating core genome images.  This is probably due to the default memory limit for Java being set too low and causes large delays when there's lots of contigs to generate images for.

**Comment by apetkau** [comment]
This was partially fixed in by adjusting the `vcf2core_numcpus` setting in https://github.com/apetkau/core-phylogenomics/blob/aa29c9a9d43d191da0ed2bee44ae40ad68cd9e89/etc/pipeline.conf.default#L35.  This reduces the number of GView images `fork`ed at any given time, but I would still like to see a more permanent solution.

**Comment by apetkau** [comment]
This issue will most likely be fixed when https://github.com/apetkau/vcf2pseudoalignment/issues/12 is fixed, since generating these images was the major cause of the slow down.

**Comment by csieffert** [comment]
Gview image generation has been removed from the code, this should solve the issue.

**Comment by apetkau** [comment]
Sorry to re-open this, but could I have you send in a pull request for the code that got reverted (I believe it was this commit https://github.com/apetkau/core-phylogenomics/commit/9860c55d45646a08845f0f2c8534a0abf8ac20ae) for fixing this issue.

Also, could I then have you update the vcf2pseudoalign sub-module with you're code added in.  It should involve updating the `lib/vcf2pseudoalignment` code to the correct commit (from https://github.com/apetkau/vcf2pseudoalignment/commits/development) and then using `git add lib/vcf2pseudoalignment` and making a commit.  See http://stackoverflow.com/questions/8191299/update-a-submodule-to-the-latest-commit.

**Comment by apetkau** [comment]
This was fixed as part of #14 and https://github.com/apetkau/vcf2pseudoalignment/issues/12
